### ISSUE TITLE
Release build network connectivity issue caused by OkHttp3 and ProGuard

### ISSUE THREAD

**Issue by SirionRazzer** [lopspower/CleanRxArchitecture#2]
This is an issue I heavily struggled with - it is necessary to change package name in following lines inside the [model-rules.pro](https://github.com/lopspower/CleanRxArchitecture/blob/master/proguard/model-rules.pro) file:

`
-keep class <my-package>.domain.model.** { *; }
`
`
-keep class <my-package>.data.net.dto.** { *; }
`

**Comment by lopspower** [comment]
Yes, if you change the project's package name, you have to change it everywhere.
